### PR TITLE
Build refactor - Use FSM to track build state

### PR DESCRIPTION
**Pull request by josephharrington**
- Add an FSM implementation (based on Fysom) to track the state of a 
build.
- Remove a bunch of flags related to tracking state from the Build
class and use the FSM instead.
- Fix tests.

I've left a bunch of WIP (work-in-progess) notes since this is part of a much larger refactoring and I didn't want to do it all in one commit.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @josephharrington has signed the CLA. Thanks for the pull request!

**Comment by josephharrington** [comment]
Note that I haven't added any tests since this should be pretty much a pure refactoring of the current build logic. I have also checked change this against our test cluster/job and confirmed that everything still works.

**Comment by tjlee0909** [comment]
lgtm :+1: obviously fix tests.

**Comment by tjlee0909** [comment]
Wunderbar

**Pull request merged**
