### PR TITLE
Add ATOM_START and ATOM_FINISH log events.

### PR DESCRIPTION
**Pull request by cbrenton**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @cbrenton, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by josephharrington** [comment]
:+1:

**Comment by cbrenton** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @cbrenton has just signed the CLA. Thanks, and we look forward to your contribution.

**Pull request merged**
