### PR TITLE
Fail build immediately if no atoms found.

### PR DESCRIPTION
**Pull request by tjlee0909**
This commit addresses https://github.com/box/ClusterRunner/issues/263

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @tjlee0909 has signed the CLA. Thanks for the pull request!

**Comment by josephharrington** [comment]
Nice! This is pretty clean. What were your thoughts on failing a build with no atoms vs. letting the build pass immediately? The argument in favor of passing the build is that the atomizer command was technically successful -- zero exit code -- but (maybe just for this specific build) it didn't find any atoms.

I don't think we have a good use case in production right now, but here's a contrived one: say I wanted to set up a clusterrunner job to run just on changed php files. The atomizer could be something like:
```yaml
TESTPATH: git diff --name-only HEAD~1 | grep .php
```
In a case like that I'd probably want the build to succeed even if there were no atoms. 

On the other hand I'd agree that if someone has made a mistake in their atomizer command that they might unknowingly create a job that does nothing, so failing the build is an easy way to alert for that type of mistake. I'd hope that someone creating a job for the first time is checking more than just if the build was successful or not, but it's probably not clear for new users how to do that.

I was curious about your thoughts on the above. :+1: in general.

**Comment by tjlee0909** [comment]
I agree, technically the build didn't fail. And I am also super worried that no one will parse the build results other than the failed_tests file. I decided that this is the lesser of two evils.

At the moment, the contrived case you have is an actual production use case right now. All of the 'PHPUnit-Enumerated' type jobs (there are multiple of them) parse the HEAD commit modified files in the atomization command. As you can guess, when such a job runs with the current CR version, the build hangs and the corresponding jenkins job times out. We have currently gotten around that ATM by running the atomizer command in a separate call before invoking CR, and just exiting 0 if no tests to run were found.

**Comment by tjlee0909** [comment]
Ok, had a separate conversation with Joey, and letting the build pass (in the case of no atoms found) sounds like the correct way to go. The client should be aware that, for this ClusterRunner job configuration it is possible to have 0 atoms run, and if they want to fail the build in such a scenario, then the client can check the number of subjob result directories inside the returned result tarball.

I will close this PR and create a new one that passes the build.

**Pull request closed without merging**
