### PR TITLE
Test clusterrunner unit tests via clusterrunner on Appveyor

### PR DESCRIPTION
**Pull request by aptxkid**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @aptxkid has signed the CLA. Thanks for the pull request!

**Comment by aptxkid** [comment]
Running CR unit tests via CR on Windows was stuck. I saw this in the master log.

```
[0m[1m[31m[2015-07-24 10:18:19.810] 1200 ERROR   MasterTornadoTh cluster_base_ha Exception occurred during request to /v1/build.
Traceback (most recent call last):
  File "c:\Users\sync\.virtualenvs\cr\lib\site-packages\tornado\web.py", line 1346, in _when_complete
    callback()
  File "c:\Users\sync\.virtualenvs\cr\lib\site-packages\tornado\web.py", line 1367, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "c:\Users\sync\ClusterRunner\app\util\decorators.py", line 61, in function_with_auth
    raise AuthenticationError('Message digest does not match header, message not authenticated.')
app.util.exceptions.AuthenticationError: Message digest does not match header, message not authenticated.
[0m[1m[33m[2015-07-24 10:18:19.812] 1200 WARNING MasterTornadoTh tornado.access  401 POST /v1/build (127.0.0.1) 3.00ms
```

**Comment by aptxkid** [comment]
Turns out it's because I included functional tests by accident as well.

**Comment by aptxkid** [comment]
Now it passed all the unit tests by CR. But it didn't exit for some reason.....

```
[2015-07-24 18:18] WARNING: unhandled_exception_handler: Failed at registering signal handler for SIGINFO. This is expected if ClusterRunneris running on Windows.
running cmd: ['main.py', 'slave', '--master-url', 'appvyr-win20122:43000']
Build is running. (Build id: 1)
Polling build status url: http://appvyr-win20122:43000/v1/build/1
0 of 45 subjobs are complete (0.0%).
1 of 45 subjobs are complete (2.2%).
2 of 45 subjobs are complete (4.4%).
3 of 45 subjobs are complete (6.7%).
4 of 45 subjobs are complete (8.9%).
5 of 45 subjobs are complete (11.1%).
6 of 45 subjobs are complete (13.3%).
7 of 45 subjobs are complete (15.6%).
8 of 45 subjobs are complete (17.8%).
9 of 45 subjobs are complete (20.0%).
10 of 45 subjobs are complete (22.2%).
11 of 45 subjobs are complete (24.4%).
12 of 45 subjobs are complete (26.7%).
13 of 45 subjobs are complete (28.9%).
14 of 45 subjobs are complete (31.1%).
15 of 45 subjobs are complete (33.3%).
16 of 45 subjobs are complete (35.6%).
17 of 45 subjobs are complete (37.8%).
18 of 45 subjobs are complete (40.0%).
19 of 45 subjobs are complete (42.2%).
20 of 45 subjobs are complete (44.4%).
21 of 45 subjobs are complete (46.7%).
22 of 45 subjobs are complete (48.9%).
23 of 45 subjobs are complete (51.1%).
24 of 45 subjobs are complete (53.3%).
25 of 45 subjobs are complete (55.6%).
26 of 45 subjobs are complete (57.8%).
27 of 45 subjobs are complete (60.0%).
28 of 45 subjobs are complete (62.2%).
29 of 45 subjobs are complete (64.4%).
30 of 45 subjobs are complete (66.7%).
31 of 45 subjobs are complete (68.9%).
32 of 45 subjobs are complete (71.1%).
33 of 45 subjobs are complete (73.3%).
34 of 45 subjobs are complete (75.6%).
35 of 45 subjobs are complete (77.8%).
36 of 45 subjobs are complete (80.0%).
37 of 45 subjobs are complete (82.2%).
38 of 45 subjobs are complete (84.4%).
39 of 45 subjobs are complete (86.7%).
40 of 45 subjobs are complete (88.9%).
41 of 45 subjobs are complete (91.1%).
42 of 45 subjobs are complete (93.3%).
43 of 45 subjobs are complete (95.6%).
44 of 45 subjobs are complete (97.8%).
Build is finished. (Build id: 1)
Build 1 result was NO_FAILURES
```

**Comment by aptxkid** [comment]
The test is passing locally just fine. I suspect it got stuck at downloading the artifact on Appveyor as there's no timeout. I trying various things on Appveyor to validate my hypothesis.

**Comment by aptxkid** [comment]
I inserted several log statements and seems like CR is doing fine the whole time. But somehow the process didn't exit, which I don't understand. I asked the question on AppVeyor forum: http://help.appveyor.com/discussions/problems/2590-it-hangs-when-theres-spawned-process-running-in-background

```
debug Appveyor: timeout_time 1437771746.925103
debug Appveyor: current time 1437771741.925103
debug Appveyor: download url http://appvyr-win20122:43000/v1/build/1/result
debug Appveyor: download response: <Response [200]>
debug Appveyor: got 200 status code
debug Appveyor: artifact folder created
debug Appveyor: extracting artifact
debug Appveyor: artifact extracted
debug appveyor: exit 0
```

**Comment by aptxkid** [comment]
I tried RDP to the windows VM on AppVeyor. The AppVeyor task can finish successfully as long as I kill the running Python processes (CR master and slave). I am researching if it's possible to make AppVeyor not wait in this case.

**Comment by aptxkid** [comment]
As suggested by Feodor (http://help.appveyor.com/discussions/problems/2590-it-hangs-when-theres-spawned-process-running-in-background), putting all the commands in a `.cmd` file and call that .cmd file in `test_script` section bypassed all the Appveyor logic and finished the test successfully!!

I am going to clean up the PR a little bit to make it ready for review.

**Comment by josephharrington** [comment]
:+1:

**Pull request merged**
