### PR TITLE
Rename master/slave to manager/worker

### PR DESCRIPTION
**Pull request by jamiebuilds**
#433

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @jamiebuilds, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by jamiebuilds** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @jamiebuilds has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by jamiebuilds** [comment]
Sounds like you know what you need to do now

**Comment by jamiebuilds** [comment]
ping

**Comment by josephharrington** [comment]
Hey @jamiebuilds, sorry if I wasn't clear before. Just to clarify, we are not able to merge this PR as-is because of the backward-compatibility issues I mentioned in my earlier response above. For this PR it would be great if you could add the second part of my first bullet: "add additional external interfaces for the renames so we support both old and new names during the transition."

**Comment by jamiebuilds** [comment]
I've gone above and beyond what I'm willing to contribute to this project, this is your problematic naming that you need to fix, not me.

**Pull request closed without merging**
